resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 50ms
    instances:
      bank-client: {}
  timelimiter:
    configs:
      default:
        timeoutDuration: 300ms
    instances:
      bank-client: {}
