resilience4j:
  retry:
    configs:
      conservative:
        max-attempts: 2
        wait-duration: 5s
    instances:
      inherited:
        base-config: conservative
  timelimiter:
    configs:
      short:
        timeout-duration: 500ms
    instances:
      inherited:
        base-config: short
